server {
    listen 8080;
    server_name localhost;

    root ./YoupiBanane;
    index index.html;
    client_max_body_size 10485760;

    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;
    autoindex off;

    location / {
        allow_methods GET;
    }

    location /post_body {
        allow_methods POST;
    }

    location /directory {
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        allow_methods GET POST;
        cgi_pass .bla ./cgi_test;
    }

    location /directory/ {
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        allow_methods GET POST;
        cgi_pass .bla ./cgi_test;
    }
}
