FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    g++ make libc6 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /webserv

COPY . .

RUN make re

CMD ["bash", "-c", "./webserv conf.conf & sleep 1 && ./tester http://localhost:8080"]
