server {
    listen 8080;
    server_name localhost;
    root ./www;
    index index.html;
    client_max_body_size 10485760;
    autoindex off;
    allow_methods GET;

    location / {
        root ./www;
        index index.html;
        autoindex off;
        allow_methods GET;
    }

    location /static {
        root ./www/static;
        index index.html;
        autoindex off;
        allow_methods GET;
    }

    location /listing {
        root ./www/listing;
        autoindex on;
        allow_methods GET;
    }

    location /noindex {
        root ./www/listing;
        autoindex off;
        allow_methods GET;
    }

    location /upload {
        root ./www/uploads;
        autoindex off;
        allow_methods GET POST DELETE;
        upload_store ./www/uploads;
    }

    location /redirect/42-intra {
        return 302 https://intra.42.fr/;
    }

    location /method {
        root ./www;
        index index.html;
        autoindex off;
        allow_methods GET;
    }
}
