server {
    listen 9092;
    root ./www;
    index index.html;
    location / {
        root ./www;
        index index.html;
        allow_methods GET;
    }
}
server {
    listen 9092;
    root ./www/static;
    index index.html;
    location / {
        root ./www/static;
        index index.html;
        allow_methods GET;
    }
}